instances:
  guild id: # Guild integer id without quotes
    admin_user_id: # Error messages related to this guild will be DM'd to this user id (integer)
    db_name: 
    db_password: 
    db_user: 
  guild id: # Guild integer id without quotes
    admin_user_id: # Error messages related to this guild will be DM'd to this user id (integer)
    db_name: 
    db_password: 
    db_user: 

token: Get this from the Discord developer portal
master_admin_user_id: # Error messages not specific to any guild will be DM'd to this user id (integer)
