instances:
  guild1_id_without_quotes:
    autodelete_channels:
    - channel: channel1_name
      callback_interval_minutes: 60
      delete_older_than_minutes: 1440
    - channel: channel2_name
      callback_interval_minutes: 60
      delete_older_than_minutes: 1440
  guild2_id_without_quotes:
    autodelete_channels:
    - channel: channel1_name
      callback_interval_minutes: 60
      delete_older_than_minutes: 1440
    - channel: channel2_name
      callback_interval_minutes: 60
      delete_older_than_minutes: 1440
token: get this from discord developer website
