version: '3'

# TODO: works for single-server config only
services:
  # Discord Bot service
  bot:
    image: poly-bot-dev-env:latest  # replace with your actual bot image name and tag
    environment:
      - DATABASE_HOST
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_NAME
    command: ["wait-for-it/wait-for-it.sh", "${DATABASE_HOST}:3306", "--", "python", "bot.py"]
    depends_on:
      - db

  # MariaDB service
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
